### ISSUE TITLE
Howto ... Linux?

### ISSUE THREAD

**Issue by rogc** [Puchaczov/Musoq#3]
This is a really interesting code. But if I wanted to run it on linux, what should I do?

**Comment by Puchaczov** [comment]
I think the only what you need is to install .NET Core for linux:

https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x

then, it's probably the same as for windows.

but please have in mind that I haven't tested it on linux yet and I don't have access to machine with linux right now, I expect that some problems will occur (especially with reflection), maybe with Roslyn itself. It's difficult to determine what will happen when I will testing it on Linux. 

I could try probably this week to run it firstly on VM with Ubuntu, then I will try to run it on Raspberry Pi.

**Comment by Puchaczov** [comment]
Musoq can finally runs on ubuntu!.

![musoq-runs-on-ubuntu](https://user-images.githubusercontent.com/6973258/43488463-2a76cbc2-951a-11e8-9b94-ec9a0f414883.png)
